SELECT
    -- 🔑 Primary Key & Foreign Keys
    MD5(CONCAT(GAME_PK, '_', AT_BAT_NUMBER, '_', PITCH_NUMBER)) AS PITCH_SK,
    GAME_PK,
    PITCHER_NAME AS PITCHER_ID,
    BATTER_NAME AS BATTER_ID,
    PITCH_TYPE,

    --  Context & Pitch Sequence
    AT_BAT_NUMBER,
    PITCH_NUMBER,
    --PITCH_COUNT AS PITCHER_GAME_PITCH_COUNT,
    INNING,
    INNING_TOPBOT,
    OUTS_WHEN_UP,
    BALLS,
    STRIKES,
    N_THRUORDER_PITCHER,
    N_PRIORPA_THISGAME_PLAYER_AT_BAT,
    PITCHER_DAYS_SINCE_PREV_GAME,

    --  Game State & Defensive Alignment
    HOME_SCORE,
    AWAY_SCORE,
    BAT_SCORE_DIFF,
    IF_FIELDING_ALIGNMENT,
    OF_FIELDING_ALIGNMENT,

    -- ⚾ Pitch Tracking & Kinematics (Physical Measurements)
    RELEASE_SPEED,
    RELEASE_SPIN_RATE,
    RELEASE_EXTENSION,
    RELEASE_POS_X,
    RELEASE_POS_Y,
    RELEASE_POS_Z,
    SPIN_AXIS,
    ZONE,
--    INITIAL_VELOCITY_HORIZONTAL,
--    INITIAL_VELOCITY_VERTICAL,
 --   ACCELERATION_HORIZONTAL,
--    ACCELERATION_VERTICAL,
    API_BREAK_Z_WITH_GRAVITY,
    API_BREAK_X_ARM,
    API_BREAK_X_BATTER_IN,

    -- 💥 Batted Ball & Contact Metrics
    PITCH_RESULT,
    TYPE AS PITCH_CATEGORY, -- 'S' (Strike), 'B' (Ball), 'X' (In play)
    HIT_LOCATION,
    LAUNCH_SPEED,
    LAUNCH_ANGLE,
    HIT_DISTANCE_SC,
    LAUNCH_SPEED_ANGLE,

    -- 📈 Estimated & Expected Value Metrics (xStats)
    ESTIMATED_BA_USING_SPEEDANGLE AS XBA,
    ESTIMATED_WOBA_USING_SPEEDANGLE AS XWOBA,
    ESTIMATED_SLG_USING_SPEEDANGLE AS XSLG,
    WOBA_VALUE,
    BABIP_VALUE,
    DELTA_PITCHER_RUN_EXP,
    PLAY_DESCRIPTION

FROM {{ ref('query_log') }}