version: 2

models:
  - name: stg_statcast_pitches
    description: "Cleaned Statcast pitch-level dataset and game details."

    columns:
      - name: BATTER_NAME
        tests:
          - not_null

      - name: PITCHER_NAME
        tests:
          - not_null

      - name: STAND
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['R', 'L']

      - name: P_THROWS
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['R', 'L']

      - name: HOME_TEAM
        tests:
          - not_null

      - name: AWAY_TEAM
        tests:
          - not_null

      - name: HIT_LOCATION
        tests:
          - not_null

      - name: release_speed
        description: "Release speed of the pitch in mph."
        tests:
          - not_null

      - name: RELEASE_SPIN_RATE
        description: "Raw spin rate of the individual pitch in RPM."
        tests:
          - not_null
      - name: API_BREAK_X_ARM
        tests:
          - not_null
      - name: ARM_ANGLE
        tests:
          - not_null

      