{% macro statcast_excluded_columns() %}
    GAME_DATE, BATTER, FIELDER_2, FIELDER_3, FIELDER_4, FIELDER_5, 
    FIELDER_6, FIELDER_7, FIELDER_8, FIELDER_9,
    ON_1B, ON_2B, ON_3B, PITCHER, PFX_X, PFX_Z, PLATE_X, PLATE_Z,
    HC_X, HC_Y, TFS_DEPRECATED, TFS_ZULU_DEPRECATED, UMPIRE, PLAYER_NAME,
    SV_ID, ISO_VALUE, DELTA_HOME_WIN_EXP, DELTA_RUN_EXP, AGE_PIT_LEGACY, AGE_BAT_LEGACY,
    BATTER_DAYS_SINCE_PREV_GAME, BATTER_DAYS_UNTIL_NEXT_GAME, PITCHER_DAYS_UNTIL_NEXT_GAME,
    ATTACK_ANGLE, ATTACK_DIRECTION, SWING_PATH_TILT, INTERCEPT_BALL_MINUS_BATTER_POS_X_INCHES,
    INTERCEPT_BALL_MINUS_BATTER_POS_Y_INCHES, BAT_SCORE, FLD_SCORE, POST_BAT_SCORE, POST_FLD_SCORE, DES, BB_TYPE, EVENTS,
    DESCRIPTION, SPIN_DIR, SPIN_RATE_DEPRECATED, BREAK_ANGLE_DEPRECATED, BREAK_LENGTH_DEPRECATED, SZ_TOP, SZ_BOT, WOBA_DENOM,
    HOME_SCORE_DIFF, HOME_WIN_EXP, GAME_PK, PITCH_TYPE,BAT_SPEED,SWING_LENGTH, HYPER_SPEED,BAT_WIN_EXP,VX0,VZ0,AX,AZ,VY0,AY
{% endmacro %}